#!/bin/bash

set -eo pipefail

#[[ -d /app ]] || mkdir -p /app
#cd /app

mkdir -p /app/.profile.d

if [[ -f "$1" ]]; then
  #ruby -e "require 'yaml';(YAML.load_file('$1')['env'] || {}).each{|k,v| puts \"export #{k}='#{v}'\"}" > /app/.profile.d/00_config_vars.sh
  ruby -e "require 'yaml';(YAML.load_file('$1')['env'] || {}).each{|k,v| puts \"export #{k}\"}" > /app/.profile.d/00_config_vars.sh
  ruby -e "require 'yaml'; puts Array(YAML.load_file('$1')['dependencies']).join(\"\\n\")" > /app/.profile.d/100_dependences.sh
fi

SCRIPT_FILE=$1.build_script.sh

ruby -e "require 'yaml';puts Array(YAML.load_file('$1')['script']).join(\"\\n\")" > $SCRIPT_FILE

/build/exec $SCRIPT_FILE
